#- name: Add puma-manager
#  template: src=puma-manager.j2 dest=/etc/init/puma-manager.conf force=yes mode=755
#  tags: puma
#
#- name: Add puma config
#  template: src=etc_puma.conf.j2 dest=/etc/puma.conf force=yes mode=755
#  tags: puma
#
#- name: Add puma init script
#  template: src=etc_init_puma.j2 dest=/etc/init/puma.conf force=yes mode=755
#  tags: puma
#
#- name: Add puma shared/config
#  template: src=puma_production.j2 dest={{deploy_directory}}/shared/config/puma/production.rb force=yes mode=755
#  tags: puma

- name: Make shared/tmp/sockets
  file: 
    path: "{{deploy_directory}}/shared/tmp/sockets"
    group: "{{ deploy_user }}" 
    owner: "{{ deploy_user }}" 
    state: directory
  tags: tmp

- name: Add puma systemd service
  template: 
    src: app.service.j2 
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    group: root 
    force: yes 
    mode: 755
  tags: puma

- name: Reload systemd
  systemd: name="{{ app_name }}.service" state=started enabled=yes daemon_reload=yes
