---
# Ruby from source playbook (https://github.com/jgrowl/ansible-playbook-ruby-from-src)
- name: Update cache and packages 
  apt: update_cache=yes upgrade=dist

- name: install ruby dependencies
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - automake
    - bison
    - autoconf
    - pkg-config
    - libreadline6
    - libreadline6-dev
    - openssl
    - libssl-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev
    - curl

- name: Install app dependencies
  apt: name={{item}} state=latest
  with_items:
    - libpq-dev
    - nodejs
    - imagemagick
  tags: package

# Install correct version of ruby from source
- name: ruby-from-src | ensure directory temporary ruby download directory is present
  file: state=directory path={{rubyTmpDir}}

- name: ruby-from-src | Download ruby source
  get_url: url={{rubyUrl}} dest={{rubyTmpDir}}

- name: ruby-from-src | ensure ruby is extracted
  unarchive: "src={{rubyTmpDir}}/{{ rubyCompressedFile }} dest={{ rubyTmpDir }} copy=no"
  #command: tar -xf {{rubyCompressedFile}} chdir={{rubyTmpDir}} creates={{tmpRubyPath}}

#- name: ruby-from-src | ensure ruby is configured
#  command: ./configure chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/Makefile
#
#- name: ruby-from-src | ensure ruby is compiled
#  command: make chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/ruby
#  retries: 0
#  delay: 550 
#  ignore_errors: yes
#
#- name: ruby-from-src | ensure ruby is installed
#  command: make install chdir={{tmpRubyPath}} creates=/usr/local/bin/ruby

- name: Install ruby
  command: "{{ item }} chdir={{ rubyTmpPath }}"
  with_items:
    - ./configure
    - /usr/bin/make
    - /usr/bin/make install

- name: Install Bundler
  command: gem install bundler
