- name: Setup config/secret.yml
  template:
    src: secret.yml.j2
    dest: "{{ deploy_directory }}/shared/config/secrets.yml"
    owner: "{{ deploy_user }}" 
    group: "{{ deploy_user }}" 
    mode: 0400
