- name: Check remote ec2
  ec2_remote_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Name": "{{ app_name }}"
  register: ec2_running
  
- name: Add ec2 instances to host group
  add_host:
    hostname: '{{ ec2_running["instances"][0]["public_dns_name"] }}'
    groupname: "{{ ec2_hosts }}"
  when: ec2_running["instances"] != ""

- block:
  - name: Launch instance
    ec2:
      key_name: "{{ ec2_keypair }}"
      group: "{{ ec2_sg_name }}"
      instance_type: "{{ ec2_type }}"
      image: "{{ ec2_ami }}"
      region: "{{ ec2_region }}"
      wait: true
      instance_tags:
        Name: "{{ app_name }}"
      exact_count: 1
      count_tag: "{{ app_name }}" 
    register: ec2_info
  
  - name: Add ec2 instances to host group
    add_host:
      hostname: "{{ item.public_dns_name }}"
      groupname: "{{ ec2_hosts }}"
    with_items: "{{ ec2_info.instances }}"
  
  - name: Wait for ssh to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    with_items: "{{ ec2_info.instances }}"
  
  when: ec2_running["instances"] == ""

